# Folder paths
meeting_recordings_folder: "meeting_recording_queue"
processed_video_folder: "processed_video_files"
processed_audio_folder: "processed_audio_files"
transcripts_folder: "transcripts"
summaries_folder: "summaries"
summary_type_presets_folder: "summary_type_presets"


# Whisper settings
whisper:
  model: "medium"
  language: "auto"  # Set to a specific language code or "auto" for automatic detection
  device: "cuda"    # Options: "auto", "cpu", "cuda"
  batch_size: "auto"  # "auto" or an integer
  use_fp16: "auto"    # "auto", true, or false
  segment_length: "auto"  # "auto" or an integer (seconds)

llm:
  model: "xtuner/llava-phi-3-mini-gguf"
  client_type: "local_openai"
  max_tokens: 6000
  temperature: 0.7
  base_url: "http://localhost:1234/v1" #only use this if using something like lm studio and local llms

# Summary settings
summary_type: "meeting"  # This should match a key in the 'system_prompts' section
